//Lista de registros para teste da aplicação.

let listaRegistros = [
    {"categoria": "BackEnd",
    "descricao": "Aprenda e use o Typescript",
    "id": 1,
    "linguagem":"Typescript",
    "titulo" : "Use typescript",
    "video" : ""},
   {"categoria": "FrontEnd",
    "descricao": "Use bibliotecas de estilo como o Bootstrap e o Materil UI",
    "id": 2,
    "linguagem":"React",
    "titulo" : "Use bibliotecas de estilo",
    "video" : ""},
   {"categoria": "Comportamental",
    "descricao": "Exercite sua persistência, não desista na primeira dificuldade.",
    "id": 3,
    "linguagem":"Persistência",
    "titulo" : "Exercite sua persistência",
    "video" : ""},
   {"categoria": "Comportamental",
    "descricao": "Para programar você precisa ser paciente, pois nem sempre as coisas vão dar certo de primeira",
    "id": 4,
    "linguagem":"Paciência",
    "titulo" : "Seja paciente",
    "video" : ""},
   {"categoria": "Comportamental",
    "descricao": "Curiosidade é uma excelente virtude para programadores, sendo curioso você aprende muitos",
    "id": 5,
    "linguagem":"Curiosidade",
    "titulo" : "Seja curioso",
    "video" : ""},
   {"categoria": "FullStack",
    "descricao": "Leia a documentação da linguagem/framework/biblioteca, pois costuma ser completa e correta ",
    "id": 6,
    "linguagem":"Documentação",
    "titulo" : "Leia a documentação",
    "video" : ""},
   {"categoria": "FullStack",
    "descricao": "Explore as funcionalidade do inspecionar do seu navegador, você aprenderá muito sobre seu código usando o inspecionar",
    "id": 7,
    "linguagem":"Inspecionar",
    "titulo" : "Abuse do inspecionar",
    "video" : ""},
   {"categoria": "FullStack",
    "descricao": "Pense na acessibilidade da sua aplicação, é importante que ela seja contruída pensando em todas pessoas. Você pode usar o inspecionar no Lighthouse para checá-la.",
    "id": 8,
    "linguagem":"Acessibilidade",
    "titulo" : "Acessibilidade",
    "video" : ""},
   {"categoria": "FullStack",
    "descricao": "Aprenda inglês, a maior parte dos conteúdos disponíveis é em inglês, especialmente quando se trata de novidades. Além disso, se você souber falar inglês poderá encotrar oportunidades de trabalho em empresas em outros países. ",
    "id": 9,
    "linguagem":"Inglês",
    "titulo" : "Aprenda inglês",
    "video" : ""},
   {"categoria": "FullStack",
    "descricao": "Abuse das extensões nos seu editor de código. Bons exemplos: Prettier, Live Server",
    "id": 10,
    "linguagem":"Extensões",
    "titulo" : "Use extensões",
    "video" : ""},
   {"categoria": "Comportamental",
    "descricao": "Existem bons conteúdos que podem ser acessados de forma gratuita no youtube. Aproveite!",
    "id":11,
    "linguagem": "Aprendizado",
    "titulo": "Use o Youtube",
    "video": "https://www.youtube.com/",
    },
    {"categoria": "FullStack",
    "descricao": "Para ser um programador você precisa entender as diversas camadas que estão por trás do que você está fazendo.",
    "id":12,
    "linguagem": "Fundamentos",
    "titulo": "Tenha fundamentos",
    "video": "https://www.youtube.com/watch?v=22nd99SLgNA",
    },
    {"categoria": "FrontEnd",
    "descricao": "Através das redes sociais você pode acompanhar os profissionais que são referencia em seu ramo. Um bom exemplo é o Diego da RockeatSeat, que é referência em React.",
    "id":13,
    "linguagem": "Conhecimento",
    "titulo": "Siga os bons",
    "video": "https://www.youtube.com/watch?v=pmXfvd6Zqg4",
    }
];

localStorage.setItem("DevTips", JSON.stringify(listaRegistros));


